# Generated by Django 4.0.2 on 2022-02-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Дирекция')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Служба/направление/управление')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('work_phone', models.CharField(max_length=16, verbose_name='Номер рабочего телефона')),
                ('cell_phone', models.CharField(max_length=16, verbose_name='Номер сотового телефона')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.department')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.directory')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.position')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.service')),
            ],
        ),
    ]
