# Generated by Django 4.0.2 on 2022-04-21 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': (), 'permissions': [('add_position', 'Добавление отдела'), ('delete_position', 'Удаление отдела')]},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': (), 'permissions': [('add_position', 'Добавление департамента'), ('delete_position', 'Удаление департамента')]},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'default_permissions': (), 'permissions': [('add_position', 'Добавление дирекции'), ('delete_position', 'Удаление дирекции')]},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'default_permissions': (), 'permissions': [('add_position', 'Добавление должности'), ('delete_position', 'Удаление должности')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'permissions': [('add_position', 'Добавление службы/направления/управления'), ('delete_position', 'Удаление службы/направления/управления')]},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'default_permissions': (), 'permissions': [('download_data', 'Выгрузка данных'), ('change_worker', 'Изменение данных сотрудника')]},
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
