# Generated by Django 4.0.2 on 2022-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0004_groupauxperm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': (), 'permissions': (('add_branch', 'Добавление отдела'), ('delete_branch', 'Удаление отдела')), 'verbose_name': 'Отдел'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': (), 'permissions': (('add_department', 'Добавление департамента'), ('delete_department', 'Удаление департамента')), 'verbose_name': 'Департамент'},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'default_permissions': (), 'permissions': (('add_directory', 'Добавление дирекции'), ('delete_directory', 'Удаление дирекции')), 'verbose_name': 'Дирекция'},
        ),
        migrations.AlterModelOptions(
            name='groupauxperm',
            options={'default_permissions': (), 'permissions': (('add_group', 'Добавление группы'), ('delete_group', 'Удаление группы'), ('edit_group', 'Изменение группы')), 'verbose_name': 'Группа пользователей'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'default_permissions': (), 'permissions': (('add_position', 'Добавление должности'), ('delete_position', 'Удаление должности')), 'verbose_name': 'Должность'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'permissions': (('add_service', 'Добавление службы/направления/управления'), ('delete_service', 'Удаление службы/направления/управления')), 'verbose_name': 'Служба/Направление/Управление'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'default_permissions': (), 'permissions': (('download_data', 'Выгрузка данных'), ('change_worker', 'Изменение данных сотрудника')), 'verbose_name': 'Сотрудник'},
        ),
    ]
