# Generated by Django 4.0.2 on 2022-05-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0005_alter_branch_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'default_permissions': (), 'permissions': (('download_data', 'Выгрузка данных'), ('change_worker', 'Изменение данных сотрудника'), ('search_worker', 'Поиск сотрудников')), 'verbose_name': 'Сотрудник'},
        ),
    ]
