# Generated by Django 4.0.2 on 2022-05-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0006_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'default_permissions': (), 'permissions': (('download_data', 'Выгрузка данных'), ('change_worker', 'Изменение данных сотрудника'), ('search_worker', 'Поиск сотрудников'), ('assign_group', 'Назначение групп привилегий')), 'verbose_name': 'Сотрудник'},
        ),
    ]
