# Generated by Django 4.0.2 on 2022-05-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0008_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': (), 'permissions': (('add_branch', 'Добавление отдела'), ('delete_branch', 'Удаление отдела'), ('edit_branch', 'Изменение отдела')), 'verbose_name': 'Отдел'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': (), 'permissions': (('add_department', 'Добавление департамента'), ('delete_department', 'Удаление департамента'), ('edit_department', 'Изменение департамента')), 'verbose_name': 'Департамент'},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'default_permissions': (), 'permissions': (('add_directory', 'Добавление дирекции'), ('delete_directory', 'Удаление дирекции'), ('edit_directory', 'Изменение дирекции')), 'verbose_name': 'Дирекция'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'default_permissions': (), 'permissions': (('add_position', 'Добавление должности'), ('delete_position', 'Удаление должности'), ('edit_position', 'Изменение должности')), 'verbose_name': 'Должность'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'permissions': (('add_service', 'Добавление службы/направления/управления'), ('delete_service', 'Удаление службы/направления/управления'), ('edit_service', 'Изменение службы/направления/управления')), 'verbose_name': 'Служба/Направление/Управление'},
        ),
    ]
